# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_spec/topic_analysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_spec/topic_analysis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!service_spec/topic_analysis.proto\"e\n\x0bPLSARequest\x12\x0c\n\x04\x64ocs\x18\x01 \x03(\t\x12\x12\n\nnum_topics\x18\x02 \x01(\x12\x12\x15\n\rtopic_divider\x18\x03 \x01(\x12\x12\x0f\n\x07maxiter\x18\x04 \x01(\x12\x12\x0c\n\x04\x62\x65ta\x18\x05 \x01(\x01\"\x1f\n\x08\x46loatRow\x12\x13\n\x0b\x64oubleValue\x18\x01 \x03(\x01\"?\n\x0cPLSAResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06handle\x18\x03 \x01(\t26\n\rTopicAnalysis\x12%\n\x04PLSA\x12\x0c.PLSARequest\x1a\r.PLSAResponse\"\x00\x62\x06proto3')
)




_PLSAREQUEST = _descriptor.Descriptor(
  name='PLSARequest',
  full_name='PLSARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='docs', full_name='PLSARequest.docs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_topics', full_name='PLSARequest.num_topics', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_divider', full_name='PLSARequest.topic_divider', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxiter', full_name='PLSARequest.maxiter', index=3,
      number=4, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta', full_name='PLSARequest.beta', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=138,
)


_FLOATROW = _descriptor.Descriptor(
  name='FloatRow',
  full_name='FloatRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doubleValue', full_name='FloatRow.doubleValue', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=171,
)


_PLSARESPONSE = _descriptor.Descriptor(
  name='PLSAResponse',
  full_name='PLSAResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='PLSAResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='PLSAResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handle', full_name='PLSAResponse.handle', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=236,
)

DESCRIPTOR.message_types_by_name['PLSARequest'] = _PLSAREQUEST
DESCRIPTOR.message_types_by_name['FloatRow'] = _FLOATROW
DESCRIPTOR.message_types_by_name['PLSAResponse'] = _PLSARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PLSARequest = _reflection.GeneratedProtocolMessageType('PLSARequest', (_message.Message,), dict(
  DESCRIPTOR = _PLSAREQUEST,
  __module__ = 'service_spec.topic_analysis_pb2'
  # @@protoc_insertion_point(class_scope:PLSARequest)
  ))
_sym_db.RegisterMessage(PLSARequest)

FloatRow = _reflection.GeneratedProtocolMessageType('FloatRow', (_message.Message,), dict(
  DESCRIPTOR = _FLOATROW,
  __module__ = 'service_spec.topic_analysis_pb2'
  # @@protoc_insertion_point(class_scope:FloatRow)
  ))
_sym_db.RegisterMessage(FloatRow)

PLSAResponse = _reflection.GeneratedProtocolMessageType('PLSAResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLSARESPONSE,
  __module__ = 'service_spec.topic_analysis_pb2'
  # @@protoc_insertion_point(class_scope:PLSAResponse)
  ))
_sym_db.RegisterMessage(PLSAResponse)



_TOPICANALYSIS = _descriptor.ServiceDescriptor(
  name='TopicAnalysis',
  full_name='TopicAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=238,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='PLSA',
    full_name='TopicAnalysis.PLSA',
    index=0,
    containing_service=None,
    input_type=_PLSAREQUEST,
    output_type=_PLSARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPICANALYSIS)

DESCRIPTOR.services_by_name['TopicAnalysis'] = _TOPICANALYSIS

# @@protoc_insertion_point(module_scope)
